version: "3.0"
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgresql-database-vot
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: VOT

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-backend-vot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react-frontend-vot
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
      - postgres
    restart: on-failure





